# Generated by Django 5.1.3 on 2024-12-01 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='members_max',
            field=models.IntegerField(default=1),
        ),
    ]
