# Generated by Django 5.1.3 on 2024-12-01 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_room_members_max'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participation',
            name='is_blocked',
            field=models.IntegerField(null=True),
        ),
    ]
