# Generated by Django 5.1.3 on 2024-11-25 23:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(choices=[('text', 'Text'), ('file', 'File'), ('link', 'Link')], max_length=10)),
                ('participation_id', models.ForeignKey(db_column='participation_id', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='rooms.participation')),
            ],
            options={
                'db_table': 'messages',
            },
        ),
    ]
