# Generated by Django 5.1.3 on 2024-11-22 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(choices=[('text', 'Text'), ('file', 'File'), ('link', 'Link')], max_length=10)),
            ],
            options={
                'db_table': 'messages',
                'managed': False,
            },
        ),
    ]
